### ISSUE TITLE
Okay to include bulmo-o-steps in our web app builder?

### ISSUE THREAD

**Issue by gragland** [octoshrimpy/bulma-o-steps#13]
Hey, I'm interested in including bulmo-o-steps in the component library of our Bulma web app builder so users can easily drop it into their projects. I don't want to self-promote, so won't include the link, but if you could email me at gabe.ragland@gmail.com I'd love to discuss.

![Screen Shot 2019-04-04 at 7 04 23 PM](https://user-images.githubusercontent.com/1481077/55599607-6d36a580-570d-11e9-8e38-b32ff6324ff5.png)

**Comment by octoshrimpy** [comment]
I'd love to have bulma-o-steps as a component within DivJoy! Absolutely, go for it.

**Comment by gragland** [comment]
@octoshrimpy Great! I'll add it to our component library soon. By the way, if you'd like an invite to our alpha version feel free to join our community at https://spectrum.chat/divjoy. Long-term we plan to make it very easy for anyone to create and submit new components right in our tool, so would love to hear any feedback you have.
