### ISSUE TITLE
Interferes with stock Bulma

### ISSUE THREAD

**Issue by riovir** [octoshrimpy/bulma-o-steps#15]
The extension alters various unrelated `Bulma` aspects. It most likely closely relates to [Issue #9](https://github.com/octoshrimpy/bulma-o-steps/issues/9).

The offending line(s) of code can be found [here](https://github.com/octoshrimpy/bulma-o-steps/blob/master/bulma-steps.sass#L1-L2).
They force for instance the `Button` element's [justify-content](https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L53) to revert back to `flex-start` by re-applying the [control mixin](https://github.com/jgthms/bulma/blob/master/sass/utilities/controls.sass#L22) on it.

It may be okay to include stock Bulma for a `CSS-only` output, but for projects that use `sass / scss` it actually hurts to copy the unversioned fragments of Bulma into the extension.

The minimal change to fix the issue would be simple:

Extract everything but the top import from `https://github.com/octoshrimpy/bulma-o-steps/blob/master/bulma-steps.sass` to a new file and allow projects importing that instead. This way the extension will be powered by their variables and mixins.

For backward compatibility the old `bulma-steps.sass` can simply import the new file into itself effectively being only 2-3 lines of code.

**Comment by riovir** [comment]
I've made an attempt to allow consumers of the extension to import `bulma-o-steps/index.sass` instead to be free of side effects via this pull request: https://github.com/octoshrimpy/bulma-o-steps/pull/16

**Comment by octoshrimpy** [comment]
looks good! I'm currently in the middle of rewriting the extension from scratch into separate file for easier customizing/managing, as it was pulled from aramvisser's extension, and the code was a large ball of spaghetti.
