### ISSUE TITLE
Can you publish a new version?

### ISSUE THREAD

**Issue by hegyitaho** [octoshrimpy/bulma-o-steps#20]
It's been almost a year since the last release and one important [fix](https://github.com/octoshrimpy/bulma-o-steps/issues/15) would be included.

**Comment by razorness** [comment]
There should also be a dependency update to bulma v0.8.

**Comment by riovir** [comment]
Is this project abandoned?

**Comment by riovir** [comment]
Is this project abandoned?

Even without changing anything (except probably fixing the `"main"` 
 to point to `"index.sass"` in the `package.json`) a new release would fix a lot of issues for folks already using it.

**Comment by octoshrimpy** [comment]
@riovir if you'd like to send out a PR, I'd love to review and merge!

**Comment by fgs-dbudwin** [comment]
I have submitted PR #23 that hopefully addresses a lot of the concerns mentioned in this issue.  I've update the pinned version of Bulma and addressed the concern @riovir had in his above comment.

**Comment by fgs-dbudwin** [comment]
@octoshrimpy can we publish a new version...PR #23 got merged 2 months ago.

**Comment by octoshrimpy** [comment]
@fgs-dbudwin @riovir update pushed with current PR fixes. will take a look at issues in a lil bit.
