### ISSUE TITLE
Componente bulma steps no funciona

### ISSUE THREAD

**Issue by rvegaj** [octoshrimpy/bulma-o-steps#21]
El componente bulma-steps no funciona adecuadamente. Solo se muestra el texto sin las clases de bulma. Gracias
![image](https://user-images.githubusercontent.com/12112495/67238530-efb95500-f412-11e9-84c0-35cc8e9fd93f.png)

**Comment by D0C702WH0** [comment]
+1



![image](https://user-images.githubusercontent.com/37305474/68216414-254c6980-ffe1-11e9-8269-63734939d949.png)

![image](https://user-images.githubusercontent.com/37305474/68216547-55940800-ffe1-11e9-9b01-9596e23b6ed7.png)

**Comment by octoshrimpy** [comment]
I cannot help without being shown if the extension is properly being loaded, and what your css/html looks like. Please comment if still a problem, and I will reopen.
