### ISSUE TITLE
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by AlbertoDePena** [octoshrimpy/bulma-o-steps#46]
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($steps-marker-size, 2) or calc($steps-marker-size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
174 │       top: calc(#{$size * ($steps-marker-size / 2)} - (#{$steps-divider-size / 2}))
    │                            ^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\bulma-o-steps\index.sass 174:28         @content
    node_modules\bulma-o-steps\index.sass 16:7           @content
    node_modules\bulma\sass\utilities\mixins.sass 108:5  tablet()
    node_modules\bulma-o-steps\index.sass 14:3           steps-horizontal()
    node_modules\bulma-o-steps\index.sass 167:3          steps-size()
    node_modules\bulma-o-steps\index.sass 251:3          @import
    assets\styles.scss 29:9                              root stylesheet

WARNING: 32 repetitive deprecation warnings omitted.

**Comment by JinIgarashi** [comment]
When I built this package in sveltekit, it has the same warning.

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($steps-divider-size, 2) or calc($steps-divider-size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
140 │       left: calc(#{$size * ($steps-marker-size / 2)} - (#{$steps-divider-size / 2}))
    │                                                           ^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bulma-o-steps/index.sass 140:59                  @content
    node_modules/bulma-o-steps/index.sass 23:7                    @content
    node_modules/bulma-o-steps/styles/utilities/mixins.sass 83:5  mobile()
    node_modules/bulma-o-steps/index.sass 21:3                    steps-vertical()
    node_modules/bulma-o-steps/index.sass 132:3                   steps-size()
    node_modules/bulma-o-steps/index.sass 251:3                   @import
    node_modules/bulma-o-steps/bulma-steps.sass 3:9               @import
```

**Comment by daveHylde** [comment]
Same here after upgrading angular version. 
![image](https://user-images.githubusercontent.com/95252506/203146877-67888141-9599-4461-85d6-3dbc4037da1f.png)

**Comment by pedantic-git** [comment]
@mofe23 if your fix works for you, would you be able to raise it as a PR here? Hopefully that will help @octoshrimpy with maybe merging and releasing a new version with this fix.
