### ISSUE TITLE
is-hollow shows dividers through

### ISSUE THREAD

**Issue by octoshrimpy** [octoshrimpy/bulma-o-steps#8]
using is-hollow shows divider lines behind the marker circles. quick fix is to set the background color of each is-hollow marker to white, but I can't assume that it'll always be used on a white background. Looking for a better solution in the meantime. 

It only happens in has-content-centered though.
![](https://i.imgur.com/WUEHEtw.png)

![](https://i.imgur.com/6ZQU2iD.png)

**Comment by pera** [comment]
Hi! I was wondering if there is any update on this issue. Thanks :)

**Comment by octoshrimpy** [comment]
merged, closing. Please comment if this is not fixed on next release.
